version: "3.7"
services:
  mysql:
    container_name: bsides_ctf_old_school_sql_mysql
    image: mysql:5.7
    volumes:
      - "./mysql/init:/docker-entrypoint-initdb.d"
    environment:
      - MYSQL_ROOT_PASSWORD=toor
    network_mode: "old-school-sql-network"
  phpapp:
    build: ./php
    ports:
      - "10001:80"
    network_mode: "old-school-sql-network"

networks:
  old-school-sql-network: