version: "3.7"
services:
  sql:
    container_name: shooter-sql
    image: mysql:5.7
    volumes:
      - "./sql/init:/docker-entrypoint-initdb.d"
    environment:
      - MYSQL_ROOT_PASSWORD=toor
    network_mode: "shooter-network"

  webapp:
    build: .
    network_mode: "shooter-network"
    ports:
      - 10002:3000
    environment:
      SHOOTER_DATABASE_USERNAME: root
      SHOOTER_DATABASE_PASSWORD: toor
      SHOOTER_DATABASE_HOST: shooter-sql
      RAILS_ENV: staging
      RAILS_SERVE_STATIC_FILES: 1
    depends_on:
      - sql

  # nginx:
  #   image: nginx:1.17
  #   network_mode: "shooter-network"
  #   ports:
  #     - 10002:80
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./nginx/conf.d:/etc/nginx/conf.d

networks:
  shooter-network:
